# Generated by Django 6.1.2 on 2026-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('article_count', models.PositiveIntegerField()),
                ('purchased_at', models.DateField()),
                ('expires_at', models.DateField()),
            ],
        ),
    ]
