# Generated by Django 6.1.2 on 2026-10-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchase_at',
            new_name='purchased_at',
        ),
    ]
